# Generated by Django 5.1.5 on 2025-03-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
