# Generated by Django 5.1.5 on 2025-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("producer", models.CharField(max_length=255)),
                (
                    "duration",
                    models.IntegerField(
                        help_text="Продолжительность фильма в секундах"
                    ),
                ),
            ],
        ),
    ]
